"use client";
import { Inter } from "next/font/google";
import "./global.css";
import WebAppReady from "@/components/WebAppReady/WebAppReady";
import { TonConnectUIProvider } from "@tonconnect/ui-react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <TonConnectUIProvider
        manifestUrl="https://airy-help.netlify.app/tonconnect-manifest.json"
        actionsConfiguration={{ twaReturnUrl: "https://t.me/cryptobag_bot" }}
      >
        <WebAppReady />
        <body className={inter.className}>{children}</body>
      </TonConnectUIProvider>
    </html>
  );
}
